---
- include_tasks: read_daemon_json.yml

- name: Generate ipv6 ula network
  ip6ula:
    prefixlen: "{{ docker_ipv6_default_bridge_net_prefixlen }}"
  register: ip6
  when: docker_daemon_json_content['fixed-cidr-v6'] is not defined

- include_tasks: update_daemon_json.yml
  vars:
    data:
      fixed-cidr-v6: "{{ ip6.network | string }}"
      ipv6: "{{ docker_ipv6_enabled }}"
  when: docker_daemon_json_content['fixed-cidr-v6'] is not defined
