---
# tasks file for docker
- name: Install docker
  import_role:
    name: geerlingguy.docker

- name: Install python docker modules for ansible
  import_role:
    name: geerlingguy.pip
  vars:
    pip_install_packages:
      - name: docker
      - name: docker-compose

- name: Firewall setup
  import_tasks: firewall.yml

- name: IPv6
  import_tasks: ipv6.yml
